export const INITIAL_STATE = {
  row1: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
  row2: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
  row3: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
  row4: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
  row5: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
  row6: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
  row7: {
    item1: { value: "", owner: null },
    item2: { value: "", owner: null },
    item3: { value: "", owner: null },
    item4: { value: "", owner: null },
    item5: { value: "", owner: null },
    item6: { value: "", owner: null },
    item7: { value: "", owner: null },
  },
};
